inherit_from: config/eightyfourcodes.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'lib/rubocop/cop/gitlab_security/*.rb'
    - 'spec/rubocop/cop/gitlab_security/*.rb'
    # avoid linting installed gems when running in GitHub Actions
    - '**/vendor/bundle/**/*' 
Naming/FileName:
  Exclude:
    - lib/rubocop-eightyfourcodes.rb
RSpec/ExampleLength:
  Max: 10
